### PR TITLE
ylo2_description_model

### PR DESCRIPTION
**Pull request by elpimous**

### CODE REVIEW

**Comment by graiola** [comment]
Hi @elpimous , I can not launch your robot because I am missing `ylo2_urdf_2022_description`.

**Comment by elpimous** [comment]
Humm OK. First try!!! 😇
I'll check it tomorrow.

**Comment by graiola** [comment]
@elpimous any news? :)

**Comment by elpimous** [comment]
Yes, I have a working well one..
Didn t have time to learn how to pull request...
Trying tonight.

**Comment by elpimous** [comment]
sorry, don't use correctly github !!!
https://github.com/elpimous/ylo-2/tree/main/Wolf_for_ylo2
Can't do better for now lol

**Comment by graiola** [comment]
Salut @elpimous, can I take ylo2_description from https://github.com/elpimous/ylo-2/tree/main/Wolf_for_ylo2/wolf_descriptions/ylo2_description and add that to `wolf_descriptions`? Is that your working configuration? Thank you

**Comment by elpimous** [comment]
Of course.. Walk is stable. Stand-up a bit less, due to bad initial legs position.
Package cleanup done, and working.

**Comment by graiola** [comment]
I made some changes in the params and standup posture to increase the stability, you can try it out and see if it improves the walk on your side too :)

https://github.com/graiola/wolf_descriptions/tree/master/ylo2_description

**Comment by elpimous** [comment]
Nice!! x linear velocity is a bit slow, but limits shut down, ok.
I'd personally keep Left-Right foot distance lower, for 2 reasons :
1/ visually, it's nicer to see foots in the inside (like real spot) rather that outside (like a scrab)
2/ the force on ABAD, with feets in the inside, reduce consumption, and so let the robot walk longer.
My ideal feets L-R distance  would be equat to ABAD center motors distance. 
In real, it must be a bit lower, but less than the one who produce parallel L-R legs.
But it produces too less stability.....so...
Need to balance choice...

**Pull request closed without merging**
